from lexer import Lexer
from parser import Parser
from compiler import compile as compile_source
from vm import VM, InterpretResult
from objects import OrionComponentInstance
from renderer import TextRenderer

class Orion:
    """
    The main facade for the Orion language compiler/interpreter.
    This class ties together the different phases.
    """
    def __init__(self):
        self.vm = VM()
        self.had_error = False
        self.had_runtime_error = False

    def run(self, source: str):
        """Runs a piece of Orion source code using the new Compiler -> VM pipeline."""
        lexer = Lexer(source)
        tokens = lexer.scan_tokens()

        parser = Parser(tokens)
        statements = parser.parse()

        if not statements and len(tokens) > 1:
            return

        main_function = compile_source(statements)

        if main_function is None:
            self.had_error = True
            return

        result, last_value = self.vm.interpret(main_function)

        if result == InterpretResult.OK:
            # After the script runs, check for an 'App' component to render.
            app_instance = self.vm.globals.get("App")
            if isinstance(app_instance, OrionComponentInstance) and "render" in app_instance.definition.methods:
                self.vm.draw_commands = []  # Clear any previous commands
                self.vm.call_method_on_instance(app_instance, "render")

                # Process and render the commands generated by the render() call.
                renderer = TextRenderer(80, 24)  # Use a default canvas size
                renderer.process_commands(self.vm.draw_commands)

                print("\n--- Orion Render Output ---")
                renderer.render_to_console()
                print("---------------------------\n")


    def run_file(self, path: str):
        """Runs an Orion script from a file."""
        try:
            with open(path, 'r', encoding='utf-8') as f:
                source = f.read()
            self.run(source)
            # Exit with an error code if there was a problem.
            if self.had_error: exit(65)
            if self.had_runtime_error: exit(70)
        except FileNotFoundError:
            print(f"Error: File not found at '{path}'")
            exit(1)

    def run_prompt(self):
        """Runs an interactive REPL session."""
        print("Orion REPL (Ctrl+C to exit)")
        while True:
            try:
                line = input("> ")
                if not line: continue
                self.run(line)
                self.had_error = False # Reset error for REPL
            except KeyboardInterrupt:
                print("\nExiting.")
                break
            except EOFError:
                print("\nExiting.")
                break
